# Generated by Django 5.1.5 on 2025-02-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('gender', models.TextField(default='男')),
                ('desription', models.TextField()),
                ('headshot', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
