# Generated by Django 5.1.6 on 2025-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0003_alter_user_managers_remove_user_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_site_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
