# Generated by Django 5.1.6 on 2025-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0006_post_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
