# Generated by Django 5.1.6 on 2025-04-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0006_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('team', '團隊招募'), ('project', '作品分享')], default='team', max_length=10),
        ),
    ]
