# Generated by Django 5.1.6 on 2025-03-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0007_post_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='description',
        ),
    ]
