# Generated by Django 5.1.6 on 2025-03-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0010_post_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='watched',
        ),
    ]
