# Generated by Django 5.1.6 on 2025-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0011_remove_post_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='watched',
            field=models.IntegerField(default=0),
        ),
    ]
